// packages/convex/src/react/primitives/BillingToggle.tsx
import type { RecurringCycle } from "../../core/types.js";
import { formatRecurringCycle } from "../shared.js";
import { SegmentGroup } from "./SegmentGroup.js";

export const BillingToggle = ({
  cycles = [],
  value,
  onValueChange,
  className = "",
}: {
  cycles?: RecurringCycle[];
  value?: RecurringCycle;
  onValueChange?: (cycle: RecurringCycle) => void;
  className?: string;
}) => {
  if (cycles.length < 2) return null;

  return (
    <SegmentGroup
      items={cycles.map((cycle) => ({
        value: cycle,
        label: formatRecurringCycle(cycle),
      }))}
      value={value}
      onValueChange={(segment) => onValueChange?.(segment as RecurringCycle)}
      className={className}
    />
  );
};

// packages/convex/src/svelte/primitives/BillingToggle.svelte
<script lang="ts">
  /* global $props */
  import type { RecurringCycle } from "../../core/types.js";
  import { formatRecurringCycle } from "./shared.js";
  import SegmentGroup from "./SegmentGroup.svelte";

  interface Props {
    cycles?: RecurringCycle[];
    value?: RecurringCycle;
    onValueChange?: (cycle: RecurringCycle) => void;
    className?: string;
  }

  let { cycles = [], value, onValueChange, className = "" }: Props = $props();
</script>

{#if cycles.length > 1}
  <SegmentGroup
    items={cycles.map((cycle) => ({
      value: cycle,
      label: formatRecurringCycle(cycle),
    }))}
    value={value}
    onValueChange={(segment) => onValueChange?.(segment as RecurringCycle)}
    className={className}
  />
{/if}
