// packages/convex/src/react/primitives/CustomerPortalButton.tsx
import { useState, type PropsWithChildren } from "react";

export const CustomerPortalButton = ({
  href,
  disabled = false,
  className = "",
  onOpenPortal,
  children,
}: PropsWithChildren<{
  href?: string;
  disabled?: boolean;
  className?: string;
  onOpenPortal?: () => Promise<void> | void;
}>) => {
  const [isLoading, setIsLoading] = useState(false);

  const handleClick = async () => {
    if (disabled || isLoading || !onOpenPortal) return;
    setIsLoading(true);
    try {
      await onOpenPortal();
    } finally {
      setIsLoading(false);
    }
  };

  if (onOpenPortal) {
    return (
      <button
        type="button"
        className={`${className || "button-outline"} disabled:cursor-not-allowed disabled:opacity-60 cursor-pointer`}
        disabled={disabled}
        onClick={handleClick}
      >
        {children ?? (isLoading ? "Loading..." : "Manage billing")}
      </button>
    );
  }

  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className={className || "button-outline"}
    >
      {children ?? "Manage billing"}
    </a>
  );
};

// packages/convex/src/svelte/primitives/CustomerPortalButton.svelte
<script lang="ts">
  /* global $props, $state */
  import type { Snippet } from "svelte";

  interface Props {
    href?: string;
    disabled?: boolean;
    className?: string;
    onOpenPortal?: () => Promise<void> | void;
    children?: Snippet;
  }

  let {
    href = undefined,
    disabled = false,
    className = "",
    onOpenPortal,
    children,
  }: Props = $props();

  let isLoading = $state(false);

  const handleClick = async () => {
    if (disabled || isLoading || !onOpenPortal) return;
    isLoading = true;
    try {
      await onOpenPortal();
    } finally {
      isLoading = false;
    }
  };
</script>

{#if onOpenPortal}
  <button
    type="button"
    class={`${className || "button-outline"} disabled:cursor-not-allowed disabled:opacity-60 cursor-pointer`}
    {disabled}
    onclick={handleClick}
  >
    {#if children}
      {@render children()}
    {:else}
      {isLoading ? "Loading..." : "Manage billing"}
    {/if}
  </button>
{:else}
  <a
    href={href}
    target="_blank"
    rel="noopener noreferrer"
    class={`${className || "button-outline"}`}
  >
    {#if children}
      {@render children()}
    {:else}
      Manage billing
    {/if}
  </a>
{/if}
