// packages/convex/src/react/primitives/OneTimePaymentStatusBadge.tsx
import type { OneTimePaymentStatus } from "../../core/types.js";

const labels: Record<OneTimePaymentStatus, string> = {
  pending: "Pending",
  paid: "Paid",
  refunded: "Refunded",
  partially_refunded: "Partially refunded",
};

export const OneTimePaymentStatusBadge = ({
  status,
  className = "",
}: {
  status: OneTimePaymentStatus;
  className?: string;
}) => {
  return <span className={className}>{labels[status]}</span>;
};

// packages/convex/src/svelte/primitives/OneTimePaymentStatusBadge.svelte
<script lang="ts">
  /* global $props */
  import type { OneTimePaymentStatus } from "../../core/types.js";

  interface Props {
    status: OneTimePaymentStatus;
    className?: string;
  }

  let { status, className = "" }: Props = $props();

  const labels: Record<OneTimePaymentStatus, string> = {
    pending: "Pending",
    paid: "Paid",
    refunded: "Refunded",
    partially_refunded: "Partially refunded",
  };
</script>

<span class={className}>{labels[status]}</span>
