// packages/convex/src/react/primitives/OneTimeCheckoutButton.tsx
import type { PropsWithChildren } from "react";
import { CheckoutButton } from "./CheckoutButton.js";

export const OneTimeCheckoutButton = ({
  productId,
  href,
  disabled = false,
  className = "",
  onCheckout,
  children,
}: PropsWithChildren<{
  productId: string;
  href?: string;
  disabled?: boolean;
  className?: string;
  onCheckout?: (payload: { productId: string }) => Promise<void> | void;
}>) => (
  <CheckoutButton
    productId={productId}
    href={href}
    disabled={disabled}
    className={className}
    onCheckout={onCheckout}
  >
    {children ?? "Buy now"}
  </CheckoutButton>
);

// packages/convex/src/svelte/primitives/OneTimeCheckoutButton.svelte
<script lang="ts">
  /* global $props */
  import type { Snippet } from "svelte";
  import CheckoutButton from "./CheckoutButton.svelte";

  interface Props {
    productId: string;
    href?: string;
    disabled?: boolean;
    className?: string;
    onCheckout?: (payload: { productId: string }) => Promise<void> | void;
    children?: Snippet;
  }

  let {
    productId,
    href = undefined,
    disabled = false,
    className = "",
    onCheckout,
    children,
  }: Props = $props();
</script>

<CheckoutButton
  {productId}
  {href}
  {disabled}
  {className}
  {onCheckout}
>
  {#if children}
    {@render children()}
  {:else}
    Buy now
  {/if}
</CheckoutButton>
