// packages/convex/src/svelte/primitives/BillingGate.svelte
<script lang="ts">
  /* global $props, $derived */
  import type { Snippet } from "svelte";
  import type { AvailableAction, BillingSnapshot } from "../../core/types.js";
  import { hasBillingActionLocal } from "./shared.js";

  interface Props {
    snapshot?: BillingSnapshot | null;
    requiredActions: AvailableAction | AvailableAction[];
    children?: Snippet;
    fallback?: Snippet;
  }

  let { snapshot, requiredActions, children, fallback }: Props = $props();

  const actions = $derived(
    Array.isArray(requiredActions) ? requiredActions : [requiredActions],
  );
  const canRender = $derived(
    snapshot != null && actions.every((action) => hasBillingActionLocal(snapshot, action)),
  );
</script>

{#if canRender}
  {@render children?.()}
{:else}
  {@render fallback?.()}
{/if}

// packages/convex/src/react/primitives/BillingGate.tsx
import type { PropsWithChildren, ReactNode } from "react";
import type { AvailableAction, BillingSnapshot } from "../../core/types.js";
import { hasBillingActionLocal } from "../shared.js";

export const BillingGate = ({
  snapshot,
  requiredActions,
  fallback = null,
  children,
}: PropsWithChildren<{
  snapshot?: BillingSnapshot | null;
  requiredActions: AvailableAction | AvailableAction[];
  fallback?: ReactNode;
}>) => {
  if (!snapshot) {
    return <>{fallback}</>;
  }

  const actions = Array.isArray(requiredActions)
    ? requiredActions
    : [requiredActions];
  const canRender = actions.every((action) =>
    hasBillingActionLocal(snapshot, action),
  );
  return <>{canRender ? children : fallback}</>;
};
