// packages/convex/src/svelte/primitives/CheckoutButton.svelte
<script lang="ts">
  /* global $props, $state */
  import type { Snippet } from "svelte";

  interface Props {
    productId: string;
    href?: string;
    disabled?: boolean;
    className?: string;
    onCheckout?: (payload: { productId: string }) => Promise<void> | void;
    children?: Snippet;
  }

  let {
    productId,
    href = undefined,
    disabled = false,
    className = "",
    onCheckout,
    children,
  }: Props = $props();

  let isLoading = $state(false);

  const handleClick = async () => {
    if (disabled || isLoading || !onCheckout) return;
    isLoading = true;
    try {
      await onCheckout({ productId });
    } finally {
      isLoading = false;
    }
  };
</script>

{#if onCheckout}
  <button
    type="button"
    class={`button-filled disabled:cursor-not-allowed disabled:opacity-60 ${className}`}
    {disabled}
    onclick={handleClick}
  >
    {#if children}
      {@render children()}
    {:else}
      {isLoading ? "Loading..." : "Checkout"}
    {/if}
  </button>
{:else}
  <a
    href={href}
    class={`button-filled ${className}`}
  >
    {#if children}
      {@render children()}
    {:else}
      Checkout
    {/if}
  </a>
{/if}

// packages/convex/src/react/primitives/CheckoutButton.tsx
import { useState, type PropsWithChildren } from "react";

export const CheckoutButton = ({
  productId,
  href,
  disabled = false,
  className = "",
  onCheckout,
  children,
}: PropsWithChildren<{
  productId: string;
  href?: string;
  disabled?: boolean;
  className?: string;
  onCheckout?: (payload: { productId: string }) => Promise<void> | void;
}>) => {
  const [isLoading, setIsLoading] = useState(false);

  const handleClick = async () => {
    if (disabled || isLoading || !onCheckout) return;
    setIsLoading(true);
    try {
      await onCheckout({ productId });
    } finally {
      setIsLoading(false);
    }
  };

  if (onCheckout) {
    return (
      <button
        type="button"
        className={`button-filled disabled:cursor-not-allowed disabled:opacity-60 ${className}`}
        disabled={disabled}
        onClick={handleClick}
      >
        {children ?? (isLoading ? "Loading..." : "Checkout")}
      </button>
    );
  }

  return (
    <a href={href} className={`button-filled ${className}`}>
      {children ?? "Checkout"}
    </a>
  );
};
