// packages/convex/src/svelte/primitives/SegmentControl.svelte
<script lang="ts">
  import SegmentGroup from "./SegmentGroup.svelte";

  export type SegmentControlItem = {
    label: string;
    value: string;
    disabled?: boolean;
  };

  interface Props {
    items?: SegmentControlItem[];
    value?: string | null;
    defaultValue?: string;
    disabled?: boolean;
    className?: string;
    onValueChange?: (value: string) => void;
  }

  let {
    items = [],
    value = undefined,
    defaultValue = undefined,
    disabled = false,
    className = "",
    onValueChange,
  }: Props = $props();
</script>

{#if items.length > 1}
  <SegmentGroup
    {items}
    {value}
    {defaultValue}
    {disabled}
    {onValueChange}
    className={className}
  />
{/if}

// packages/convex/src/react/primitives/SegmentControl.tsx
import { SegmentGroup, type SegmentGroupItem } from "./SegmentGroup.js";

export type SegmentControlItem = SegmentGroupItem;

export const SegmentControl = ({
  items = [],
  value,
  defaultValue,
  disabled = false,
  className = "",
  onValueChange,
}: {
  items?: SegmentControlItem[];
  value?: string | null;
  defaultValue?: string;
  disabled?: boolean;
  className?: string;
  onValueChange?: (value: string) => void;
}) => {
  if (items.length <= 1) return null;

  return (
    <SegmentGroup
      items={items}
      value={value}
      defaultValue={defaultValue}
      disabled={disabled}
      onValueChange={onValueChange}
      className={className}
    />
  );
};
